name: Run on Master

on:
  push:
    branches:
      - master

jobs:
  masterOnly:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # see if the ref and sha is the same as the tag.yml
      - name: Git Ref
        run: |
          echo "${{ github.ref }}"

      - name: Git Sha
        run: |
          echo "${{ github.sha }}"
